#!/usr/bin/env bash

if [ $# -ne 2 ]; then
	echo "Usage: $0 <outputfile> <directory>"
	exit 1
fi
output_path=$1
directory=$2

directory_marker_file_extension=dirmarker
directory_marker_file=.directory.$directory_marker_file_extension

directory_marker_path=$directory/$directory_marker_file

echo "" > $output_path

# To prevent infinite recursion, skip directories that we have created - we 
# can identify those directories because they have a directory marker file 
# added by the makefile.
if [ -x $directory_marker_path ]; then
	exit 0
fi

dependency_extension=dep

dependency_directory=$(dirname $output_path)

entries=$(ls -p $directory)

echo "directory=$directory" >> $output_path
echo "dependency_directory=$dependency_directory" >> $output_path

echo "include makelib/dependency_generation.mak" >> $output_path

for entry in $entries; do
	echo "-include $dependency_directory/$entry.$dependency_extension" >> $output_path
done
