#!/usr/bin/env bash

# Output the part of the file that also applies to header files.
bash makelib/generate_h_dependencies $*

# Process command line arguments.
include_dirs=
while getopts :I: flag; do
	case "$flag" in
		I)	include_dir="${OPTARG%/}" # Remove trailing slash.
			include_dirs=$(echo -e "$include_dirs\n$include_dir")
			;;
	esac
done
shift `expr $OPTIND - 1`

marker_extension="marker"

# Remaining positional arguments are the paths.
output_path=$1
source_path=$2
object_directory=${3%/.}
source_file=$(basename $source_path)
source_directory=$(dirname $source_path)
output_directory=$(dirname $output_path)
object_path=$object_directory/$source_file.o
marker_file=$output_directory/$source_file.$marker_extension
object_dir_marker=$object_directory/.$marker_extension

# Output the rule for making the object file. Not relevant for header files.
echo "$object_path: $object_dir_marker $marker_file" >> $output_path
echo "" >> $output_path

# Output the list of objects (there is only one here!).
echo "objects=$object_path" >> $output_path
