#!/usr/bin/env bash

if [ $# -ne 2 ]; then
	echo "Usage: $0 <outputfile> <directory>"
fi

dependency_extension=dep

output_path=$1
directory=$2
dependency_directory=$(dirname $output_path)

#subdirectories=$(find . -maxdepth 1 -mindepth 1 -type d -not -iname ".git")
entries=$(ls -p $directory)

echo "" > $output_path

echo "directory=$directory" >> $output_path
echo "dependency_directory=$dependency_directory" >> $output_path

echo "include makelib/dependency_generation.mak" >> $output_path

for entry in $entries; do
	echo "-include $dependency_directory/$entry.$dependency_extension" >> $output_path
done
